### ISSUE TITLE
not support MP4?"error":"FFmpegDemuxer: no supported streams"

### ISSUE THREAD

**Issue by trsheng** [jcefbuild/java-cef-build#4]
I just got an error with "FFmpegDemuxer: no supported streams",while thie web site contains MP4 file. but it works fine, while the web site contains ogg file.

**Comment by smac89** [comment]
@trsheng sorry but this is not the place to raise such issues. We deal mainly with building JCEF not debugging it.
You should raise your issue here https://bitbucket.org/chromiumembedded/java-cef/issues

Thanks

**Comment by FriwiDev** [comment]
This is actually a build related issue, as mp4 requires the build to be executed with proprietary codecs enabled.

See: https://magpcss.org/ceforum/viewtopic.php?f=6&t=13515

**Comment by FriwiDev** [comment]
@smac89 This is actually a build related issue, as mp4 requires the build to be executed with proprietary codecs enabled.

See: https://magpcss.org/ceforum/viewtopic.php?f=6&t=13515
